name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        version: ["stable", "nightly"]
    runs-on: ubuntu-latest
    name: "[${{ matrix.version }}] Test"
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.version }}

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --lib

      - run: cargo test --lib -- --include-ignored
